name: Deploy

on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install, build, and upload your site output
        uses: withastro/action@v2
        with:
          path: site
  deploy:
    uses: wlixcc/SFTP-Deploy-Action@v1.2.4
    with:
      username: ${{secrets.username}}
      server: "${{ secrets.server }}"
      password: ${{ secrets.password }}
      local_path: "./site/dist/*"
      remote_path: "${{ secrets.dir }}"
      sftp_only: true
      port: 22
