on: workflow_dispatch
name: 🚀 Deploy website
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: 🔨 Build Project
        run: |
          cd site
          npm install
          npm run build

      - name: deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{secrets.username}}
          server: "${{ secrets.server }}"
          password: ${{ secrets.password }}
          local_path: "./site/dist/*"
          remote_path: "${{ secrets.dir }}"
          sftp_only: true
          port: 22
